# Generated by Django 3.2.4 on 2021-06-12 19:52

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='brand_images/')),
            ],
            options={
                'verbose_name_plural': '4. Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=100, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category')),
            ],
            options={
                'verbose_name_plural': '1. Categories',
            },
        ),
        migrations.CreateModel(
            name='ChildSubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('child_sub_category', models.CharField(max_length=100, unique=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '3. Child sub-categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('color_code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '5. Colors',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '6. Sizes',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sub_category', models.CharField(max_length=100, unique=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'verbose_name_plural': '2. Sub-categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('product_details', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('discount_price', models.PositiveIntegerField(blank=True, default=0)),
                ('image', models.ImageField(blank=True, upload_to='products_images/')),
                ('image_url', models.CharField(blank=True, max_length=1000)),
                ('delivery_cost', models.PositiveIntegerField(blank=True, default=0)),
                ('shipping_information', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('return_policy', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('total_sells', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Unlisted', 'Unlisted'), ('Private', 'Private')], default='Published', max_length=30)),
                ('is_featured', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('child_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.childsubcategory')),
                ('color', models.ManyToManyField(blank=True, to='product.Color')),
                ('size', models.ManyToManyField(blank=True, to='product.Size')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategory')),
            ],
            options={
                'verbose_name_plural': '7. Products',
            },
        ),
        migrations.CreateModel(
            name='Multiple_Product_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products_images/')),
                ('image_url', models.CharField(blank=True, max_length=1000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Multiple Product Images',
            },
        ),
        migrations.AddField(
            model_name='childsubcategory',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
    ]
