# Generated by Django 3.2.4 on 2021-06-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_variants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '10. Reviews'},
        ),
        migrations.AlterModelOptions(
            name='multiple_product_images',
            options={'verbose_name_plural': '8. Multiple Product Images'},
        ),
        migrations.AlterModelOptions(
            name='variants',
            options={'verbose_name_plural': '9. Product Variants'},
        ),
        migrations.AddField(
            model_name='multiple_product_images',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
